describe('Julietest', () => {

	it('Should CreateCompany', () => {
		cy.visit('http://julie.zbynekrybicka.cz')
		cy.get('[data-test="LoginUsername"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="LoginPassword"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('mojeMilaJulinka')
		cy.get('[data-test="LoginButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MenuCompanies"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewCompanyButton"]:eq(' + ('0' ? '0' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="CompanyTitle"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('Priserky s.r.o.')
		cy.get('[data-test="CompanyBid"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('74967525')
		cy.get('[data-test="CompanySaveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewPersonButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="PersonFirstname"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('Zbynek')
		cy.get('[data-test="PersonLastname"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('Rybicka')
		cy.get('[data-test="PersonSaveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewPhoneButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="Phone"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('727815483')
		cy.get('[data-test="NewEmailButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="Email"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="EmailDeleteButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="PhoneDeleteButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="ContactPersonDeleteButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="BackButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
	})
	it('Should CreateRemind', () => {
		cy.visit('http://julie.zbynekrybicka.cz')
		cy.get('[data-test="LoginUsername"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="LoginPassword"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('mojeMilaJulinka')
		cy.get('[data-test="LoginButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MenuReminds"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewRemindDialogButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="RemindDescription"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('To je jen takovĂ˝ ĹˇolĂ­chĂˇnĂ­.')
		cy.get('[data-test="RemindPerson"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.select('ZbynÄ›k RybiÄŤka')
		cy.get('[data-test="RemindDeadline"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('2019-04-22')
		cy.get('[data-test="NewRemindButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="RemindListItem"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="RemindSaveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="RemindListItem"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="RemindResolveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
	})
	it('Should CreateMeeting', () => {
		cy.visit('http://julie.zbynekrybicka.cz')
		cy.get('[data-test="LoginUsername"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="LoginPassword"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('mojeMilaJulinka')
		cy.get('[data-test="LoginButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MenuMeetings"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewMeetingDialogButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingBegin"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click().then(input => input.val('2019-04-30T12:00')).click()
		cy.get('[data-test="MeetingEnd"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click().then(input => input.val('2019-04-30T13:00')).click()
		cy.get('[data-test="MeetingPersons"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.select('ZbynÄ›k RybiÄŤka')
		cy.get('[data-test="MeetingCreateButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingListItem"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingSaveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingListItem"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingResolveButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
	})
	it.only('Should OpenMeetingDialog', () => {
		cy.visit('http://julie.zbynekrybicka.cz')
		cy.get('[data-test="LoginUsername"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="LoginPassword"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('mojeMilaJulinka')
		cy.get('[data-test="LoginButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MenuMeetings"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MeetingListItem"]:eq(' + ('3' ? '3' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
	})
	it('Should CreatePayment', () => {
		cy.visit('http://julie.zbynekrybicka.cz')
		cy.get('[data-test="LoginUsername"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('zbynek.rybicka@gmail.com')
		cy.get('[data-test="LoginPassword"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('mojeMilaJulinka')
		cy.get('[data-test="LoginButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="MenuPayments"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="NewPaymentDialogButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="PaymentPerson"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.select('ZbynÄ›k RybiÄŤka')
		cy.get('[data-test="PaymentIncome"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
		cy.get('[data-test="PaymentCost"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.type('350')
		cy.get('[data-test="PaymentCreateButton"]:eq(' + ('' ? '' : '0') + ')')
			.should('have.length', 1)
			.and('be.visible')
			.click()
	})

})